language: ruby
rvm:
  - 2.2.2

before_script:
  - cp config/database_example.yml config/database.yml
  - cp config/secrets_example.yml config/secrets.yml
  - cp config/devise.rb.example config/devise.rb
  - cp config/recaptcha.rb.example config/recaptcha.rb
  - cp config/wicked_pdf.eb.example config/wicked_pdf.rb
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rake test
