language: ruby
rvm:
  - 2.0.0-p247

services:
  - mysql

before_script:
  - cp config/database_example.yml config/database.yml
  - cp config/secrets_example.yml config/secrets.yml
  - mysql -e 'create database IF NOT EXISTS roadmap_test;' -uroot
