dist: trusty
sudo: required
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

language: ruby
rvm:
  - 2.2.2

services:
  - mysql

before_script:
  - cp config/database_example.yml config/database.yml
  - cp config/secrets_example.yml config/secrets.yml
  - mysql -e 'create database IF NOT EXISTS roadmap_test;' -uroot

script:
  - bundle exec rake db:test:prepare
  - bundle exec rake
