defaults: &defaults
  
  organisation:
    name: 'My Organisation'
    abbreviation: 'MORG'
    url: 'http://your.organisation.edu/morg/'
    email: 'your.organisation@example.edu'

  application:
    name: 'DMPRoadmap'
    url: 'https://github.com/DMPRoadmap/roadmap'
  
  
development:
  <<: *defaults
  
  application:
    name: 'DMPRoadmap - DEV'
    
test:
  <<: *defaults
  
  application:
    name: 'DMPRoadmap - TEST'
    
production:
  <<: *defaults