defaults: &defaults
  organisation:
    name: 'Digital Curation Center and University of California Curation Center'
    abbreviation: 'DCC and UC3'
    url: 'https://github.com/DMPRoadmap/roadmap/wiki'
    copywrite_name: 'DCC and UC3'
    email: 'ROADMAP-L@listserv.ucop.edu'

  application:
    name: 'DMPRoadmap'
    url: 'https://github.com/DMPRoadmap/roadmap'
    version: '0.1.0'
    release_notes_url: 'https://github.com/DMPRoadmap/roadmap/wiki/Releases'

development:
  <<: *defaults
    
test:
  <<: *defaults

staging:
  <<: *defaults
    
production:
  <<: *defaults